CR-1249 Telephone capture should handle CCS cases without a uprn
ONSdigital/census-int-eq-launcher pull request #15
Opened 2020-10-13 15:19 UTC by devenrawat

Changed code to ignore UPRN check if the survey type is CCS.
https://collaborate2.ons.gov.uk/jira/browse/CR-1249

2020-10-14 15:12 UTC, cookel2 approved these changes
looks good Deven

2020-10-15 14:18 UTC, rpcatling requested changes
Looks good, just remove compilation warnings.

2020-10-15 14:18 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/eqlaunch/service/impl/TestEqLaunchService_payloadCreation.java
> +    KeyStore keyStoreEncryption = new KeyStore(JWTKEYS_ENCRYPTION);
3 unused variables here.

2020-10-15 14:51 UTC, devenrawat commented on src/test/java/uk/gov/ons/ctp/integration/eqlaunch/service/impl/TestEqLaunchService_payloadCreation.java
> +    KeyStore keyStoreEncryption = new KeyStore(JWTKEYS_ENCRYPTION);
Removed

2020-10-15 14:58 UTC, rpcatling approved these changes

2020-10-15 14:58 UTC, merged